image: debian:stable-slim

stages:
  - build

build-proj:
  stage: build
  script:
    - apt-get update -qq
    - apt-get install -y -qq build-essential autoconf automake pkg-config libssl-dev
    - autoconf --version
    - automake --version
    - gcc --version
    - pkg-config --modversion libssl
    - autoreconf -f -i -Wall
    - ./configure
    - make
